import type { PlanetId } from "./constants";

/**
 * Treści interpretacyjne dla Karak Czarowych (Dżajmini) — co znaczy KONKRETNA
 * planeta w KONKRETNEJ roli. Osiem ról × dziewięć planet = 72 krótkie,
 * osobne interpretacje, nie jeden uniwersalny opis roli (ten już jest
 * w karaki.ts jako `znaczenie`). Klucz zewnętrzny to skrót roli (AK, AmK…).
 */

export const OPISY_KARAK: Record<string, Record<PlanetId, string>> = {
  AK: {
    sun: "lekcja pokory — dusza uczy się, że blask nie pochodzi z ego, lecz z autentyczności; droga przez zmierzenie się z dumą i potrzebą uznania",
    moon: "lekcja współodczuwania — dusza uczy się troski o innych i o siebie; droga przez emocje, których nie wolno tłumić ani którym nie wolno się oddać w niewolę",
    mars: "lekcja niestosowania przemocy — dusza uczy się kierować siłę i odwagę ku obronie, nie agresji; droga przez cierpliwość",
    mercury: "lekcja prawdomówności — dusza uczy się używać słowa i intelektu w służbie prawdy; droga przez szczerość w mowie",
    jupiter: "lekcja otwartości — dusza uczy się dzielić mądrością bez wywyższania; droga przez szacunek dla cudzej ścieżki i własnych nauczycieli",
    venus: "lekcja czystości pragnień — dusza uczy się kochać bez zawłaszczania; droga przez relacje i umiar w przyjemnościach",
    saturn: "lekcja współczucia wobec cierpienia — dusza uczy się wytrwałości i dzielenia ciężaru innych; droga przez samotność, która staje się siłą",
    rahu: "lekcja rozpoznawania złudzeń — dusza wchodzi w nieznane terytoria, by nauczyć się odróżniać pragnienie od potrzeby; droga przez nienasycenie",
    ketu: "lekcja puszczania — dusza domyka stare wątki; droga przez intuicję i zgodę na to, co niedokończone",
  },
  AmK: {
    sun: "kariera budowana na widoczności i autorytecie — naturalny doradca tam, gdzie trzeba wziąć odpowiedzialność i stanąć na czele",
    moon: "powołanie związane z opieką nad ludźmi — praca dobra tam, gdzie liczy się wyczucie nastroju i elastyczność wobec zmiennych okoliczności",
    mars: "kariera wymagająca odwagi i szybkiej decyzji — doradca skuteczny w kryzysie, gorszy w powolnym, biurokratycznym tempie",
    mercury: "powołanie oparte na słowie, analizie i sieci kontaktów — naturalny doradca w sprawach wymagających precyzji i bystrości",
    jupiter: "kariera z misją — praca ma sens, gdy służy czemuś większemu niż tylko zarobek; naturalny mentor i autorytet moralny",
    venus: "powołanie związane z estetyką, dyplomacją i relacjami — praca idzie najlepiej tam, gdzie liczy się smak i takt",
    saturn: "kariera budowana latami, krok po kroku — doradca wiarygodny właśnie dlatego, że nie obiecuje skrótów",
    rahu: "powołanie nietypowe, czasem wyprzedzające epokę — kariera przez ryzyko i wejście tam, gdzie inni jeszcze się wahają",
    ketu: "praca „za kulisami”, z dystansem do rozgłosu — powołanie łatwiej rozpoznać po tym, czego dusza unika, niż czego szuka",
  },
  BK: {
    sun: "odwaga budowana na potrzebie uznania — rodzeństwo i mentorzy uczą, że siła nie musi być głośna, żeby była prawdziwa",
    moon: "odwaga płynąca z więzi — rodzeństwo i mentorzy dają oparcie emocjonalne, z którego czerpie się siłę do działania",
    mars: "odwaga wprost, bez ogródek — rodzeństwo i mentorzy uczą przez rywalizację i wspólne stawianie czoła trudnościom",
    mercury: "odwaga intelektualna — rodzeństwo i mentorzy uczą argumentować i bronić zdania, nie tylko pięści",
    jupiter: "odwaga oparta na przekonaniach — rodzeństwo i mentorzy przekazują wartości, które później stają się busolą",
    venus: "odwaga łagodzona dyplomacją — rodzeństwo i mentorzy uczą, że można postawić na swoim bez konfliktu",
    saturn: "odwaga wytrwałości, nie brawury — rodzeństwo i mentorzy bywają dalecy albo wymagający, a mimo to uczą najwięcej",
    rahu: "odwaga niekonwencjonalna — rodzeństwo albo mentorzy prowadzą na nieprzetarte ścieżki, czasem ryzykowne",
    ketu: "odwaga cicha, bez potrzeby świadków — rodzeństwo i mentorzy uczą przez to, co niedopowiedziane",
  },
  MK: {
    sun: "dom jako scena — poczucie oparcia związane z dumą z rodziny i potrzebą, by dom był czymś, co można pokazać",
    moon: "dom jako serce sprawy — matka i poczucie oparcia to najbardziej bezpośredni, naturalny fundament tej mapy",
    mars: "dom jako punkt obrony — poczucie oparcia budowane przez ochronę bliskich, czasem przez napięcia z matką",
    mercury: "dom jako miejsce rozmów — poczucie oparcia płynie z wymiany myśli, nie tylko z obecności fizycznej",
    jupiter: "dom jako źródło wartości — matka i dom przekazują sens i przekonania, które zostają na całe życie",
    venus: "dom jako azyl estetyki i spokoju — poczucie oparcia związane z pięknem otoczenia i harmonią relacji",
    saturn: "dom budowany latami, nie dany od razu — poczucie oparcia przychodzi późno, ale wtedy jest trwałe",
    rahu: "dom niestandardowy — poczucie oparcia szukane poza tradycyjnym wzorcem rodziny, czasem daleko od korzeni",
    ketu: "dom jako temat wycofania — poczucie oparcia czerpane z wewnątrz, nie z zewnętrznych okoliczności",
  },
  PiK: {
    sun: "ojciec jako autorytet — tradycja i wzorce przekazywane wprost, czasem z ciężarem oczekiwań",
    moon: "ojciec w cieniu emocji — tradycja przyjmowana albo odrzucana zależnie od tego, ile było w niej ciepła",
    mars: "ojciec jako wyzwanie do zmierzenia się — autorytety kwestionowane, dopóki nie zasłużą na szacunek czynem",
    mercury: "ojciec jako pierwszy nauczyciel — tradycja przekazywana przez rozmowę i wyjaśnianie, nie przez nakaz",
    jupiter: "ojciec jako źródło mądrości — tradycja i autorytety traktowane poważnie, czasem z nadmiernym pietyzmem",
    venus: "ojciec jako wzór relacji — tradycja przekazywana łagodnie, przez przykład, nie przymus",
    saturn: "ojciec dystansu i dyscypliny — tradycja i autorytety surowe, ale to one uczą wytrwałości",
    rahu: "ojciec nieoczywisty — tradycja przerwana albo zastąpiona własną, nietypową ścieżką",
    ketu: "ojciec jako temat niedopowiedziany — autorytety ważne bardziej przez nieobecność niż obecność",
  },
  PK: {
    sun: "twórczość jako wyraz siebie — dzieci i uczniowie uczą dzielić się uwagą, nie tylko jej wymagać",
    moon: "twórczość płynna, zmienna z nastrojem — z dziećmi i uczniami naturalna czułość i wyczucie potrzeb",
    mars: "twórczość przez działanie — dzieci i uczniowie uczą cierpliwości, bo nie reagują na rozkaz",
    mercury: "twórczość intelektualna — z dziećmi i uczniami naturalna wymiana pomysłów, czasem więcej rozmowy niż czułości",
    jupiter: "twórczość jako przekaz wartości — dzieci i uczniowie traktowani jako kontynuacja czegoś większego",
    venus: "twórczość estetyczna — z dziećmi i uczniami naturalna radość i lekkość, sztuka jako wspólny język",
    saturn: "twórczość dojrzewająca powoli — dzieci i uczniowie uczą odpowiedzialności, czasem kosztem spontaniczności",
    rahu: "twórczość nietypowa — dzieci albo uczniowie prowadzą w kierunki, których nie dało się zaplanować",
    ketu: "twórczość introwertyczna — dzieci i uczniowie uczą puszczania kontroli nad efektem końcowym",
  },
  GK: {
    sun: "rywalizacja o widoczność — krewni i przeszkody uczą, że nie każdą bitwę trzeba wygrać publicznie",
    moon: "rywalizacja emocjonalna — krewni i przeszkody wracają falami, zależnie od nastroju obu stron",
    mars: "rywalizacja wprost — krewni i przeszkody to często realny opór, który hartuje",
    mercury: "rywalizacja na słowa — krewni i przeszkody rozgrywają się bardziej w rozmowie niż w czynie",
    jupiter: "rywalizacja o rację moralną — krewni i przeszkody uczą, że nie zawsze trzeba mieć ostatnie słowo",
    venus: "rywalizacja łagodzona dyplomacją — krewni i przeszkody rzadko przeradzają się w otwarty konflikt",
    saturn: "rywalizacja długodystansowa — krewni i przeszkody nie znikają szybko, ale dają najwięcej hartu",
    rahu: "rywalizacja nieoczywista — przeszkody przychodzą znienacka, z kierunku, którego się nie spodziewano",
    ketu: "rywalizacja, z której dusza się wycofuje — przeszkody omijane raczej niż konfrontowane wprost",
  },
  DK: {
    sun: "partner jako lustro własnej dumy — związek uczy dzielić scenę, nie stać na niej samemu",
    moon: "partner jako emocjonalny dom — związek daje poczucie bezpieczeństwa, ale bywa zależny od nastroju obojga",
    mars: "partner jako równorzędny przeciwnik i sojusznik — związek żyje namiętnością, wymaga też pilnowania temperamentu",
    mercury: "partner jako rozmówca — związek opiera się na wymianie myśli, nie tylko uczuć",
    jupiter: "partner jako nauczyciel i przewodnik — związek nadaje życiu sens, czasem z nadmiernym idealizowaniem drugiej strony",
    venus: "partner jako naturalny temat — związek i harmonia relacji to jeden z głównych wątków tej mapy",
    saturn: "partner jako zobowiązanie na lata — związek dojrzewa powoli, ale bywa najtrwalszy",
    rahu: "partner nietypowy albo spoza własnego środowiska — związek jako skok w nieznane",
    ketu: "partner jako temat karmiczny — związek uczy puszczania kontroli i oczekiwań",
  },
};
